[package]
name = "kid-agentic-coding"
version.workspace = true
edition.workspace = true

[dependencies]
kid-agentic-coding-chat = { path = "../chat" }
kid-agentic-coding-session.workspace = true
ansi-to-tui.workspace = true
clap.workspace = true
clap-verbosity-flag.workspace = true
color-eyre.workspace = true
log-buffer.workspace = true
nerdicons_rs.workspace = true
ratatui.workspace = true
ratatui-textarea.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
rand.workspace = true
serde_json.workspace = true
textwrap.workspace = true
wire.workspace = true
tui-markdown.workspace = true
